### PR TITLE
S8 review card recommended basic

### PR DESCRIPTION
**Pull request by NunoDasNeves**
Very basic thumbs up/down to show whether a given review recommended the course or not.
It's pretty ugly but probably good enough for now.
Also fixed a bug with aggregating recommendations.

### CODE REVIEW

**Comment by DarkPurple141** [comment]
Should this be closed?

**Comment by DarkPurple141** [comment]
Should this be closed part 2.

**Comment by NunoDasNeves** [comment]
Electric boogaloo!

**Comment by NunoDasNeves** [comment]
@DarkPurple141 reverted the actual changes to the review card (the thumbs up/down), i figure you'll do it when you work on cards etc.
I kept the bug fix and mapping of recommended in the api util, so it's there in the store if you wanna use it.
This can be merged now I tink

**Comment by NunoDasNeves** [comment]
partially resolves #202

**Comment by NunoDasNeves** [comment]
okay now tho

**Pull request merged**
